output_workspace: "/home/clement/Documents/MVA/S2/deep_in_practice/TP1/framework_tsboard_hydra/experiment_results"

model:
    name: "dlip.models.models.LinearModel"
    args:
        input_size: 256
        hidden_size: 100
        n_layers: 1
        output_size: 10
        hidden_activ: "torch.nn.ReLU"
        output_activ: "torch.nn.Softmax"

# Training parameters
train:
    batch_size: 10
    num_epochs: 10
    eval_freq: 2
    criterion: "torch.nn.MSELoss"
    optimizer:
        name: "torch.optim.SGD"
        args:
            lr: 1e-1
            momentum: 0.9
            weight_decay: 1e-4

# Experiment parameters
exp:
    name: "Multi-classe Classification on USPS"
    data_path: "/data/raw/"
    seed: 0

hydra:
    job:
        chdir: True
    run:
        dir: ${output_workspace}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    sweep:
        dir: ${output_workspace}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
        subdir: ${hydra.job.num}
